/**
 *
 * $Id$
 */
package it.naturtalent.archiv.model.archive.validation;


/**
 * A sample validator interface for {@link it.naturtalent.archiv.model.archive.Register}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RegisterValidator
{
	boolean validate();

	boolean validateLabel(String value);
	boolean validateProjectID(String value);
	boolean validateCounter(short value);
	boolean validateNumericData(short value);
	boolean validateAlphaData(String value);
}
