/**
 *
 * $Id$
 */
package archive.validation;

import location.Adresse;

/**
 * A sample validator interface for {@link archive.Archiv}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArchivValidator
{
	boolean validate();

	boolean validateName(String value);
	boolean validateLocation(Adresse value);
}
