/**
 *
 * $Id$
 */
package archive.validation;

import archive.Archiv;
import archive.Register;
import archive.RegisterType;

import location.Adresse;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link archive.Ordner}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrdnerValidator
{
	boolean validate();

	boolean validateLabel(String value);
	boolean validateRegisters(EList<Register> value);
	boolean validateRegisterType(RegisterType value);

	boolean validateArchiv(Archiv value);

	boolean validateLocation(Adresse value);

	boolean validateId(String value);
}
